 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author proxc
 */
public class Kathigitis extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    public Kathigitis() {
        initComponents();
        viewPanel.setBackground(new java.awt.Color(35,90,190));
        //showInTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        viewPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        botPanel = new javax.swing.JPanel();
        viewTeachers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        refreshListTeachers = new javax.swing.JButton();
        eidikotitaViewCombo = new javax.swing.JComboBox<>();
        addTeachers = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        onomaLabel = new javax.swing.JLabel();
        eponimoTF = new javax.swing.JTextField();
        onomaTF = new javax.swing.JTextField();
        kataxorisiBtn = new javax.swing.JButton();
        eponimoLabel = new javax.swing.JLabel();
        eidikotitaLabel = new javax.swing.JLabel();
        eidikotitaCombo = new javax.swing.JComboBox<>();
        editTeachers = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        onomaEditLabel = new javax.swing.JLabel();
        eponimoKathigitisEditTF = new javax.swing.JTextField();
        onomaKathigitisEditTF = new javax.swing.JTextField();
        epeksergasiaEditBtn = new javax.swing.JButton();
        eponimoEditLabel = new javax.swing.JLabel();
        eidikotitaEditLabel = new javax.swing.JLabel();
        eidikotitaKathigitisEditCombo = new javax.swing.JComboBox<>();
        amEditLabel = new javax.swing.JLabel();
        amKathigitisEditTF = new javax.swing.JTextField();
        onomaLabel3 = new javax.swing.JLabel();
        diagrafiKathigitiRadio = new javax.swing.JRadioButton();
        epeksergasiaKathigitisRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/w_training_50px.png"))); // NOI18N
        jLabel15.setText(" Καθηγητές");

        viewPanel.setBackground(new java.awt.Color(45, 118, 232));
        viewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPanelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Προβολή");

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        addPanel.setBackground(new java.awt.Color(45, 118, 232));
        addPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPanelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Προσθήκη");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        editPanel.setBackground(new java.awt.Color(45, 118, 232));
        editPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPanelMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Επεξεργασία");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        botPanel.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AM", "Όνομα ", "Επώνυμο", "Ειδικότητα"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        refreshListTeachers.setText("Ανανέωση");
        refreshListTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshListTeachersActionPerformed(evt);
            }
        });

        eidikotitaViewCombo.setModel(new javax.swing.DefaultComboBoxModel<>(viewEidikotita));

        javax.swing.GroupLayout viewTeachersLayout = new javax.swing.GroupLayout(viewTeachers);
        viewTeachers.setLayout(viewTeachersLayout);
        viewTeachersLayout.setHorizontalGroup(
            viewTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTeachersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eidikotitaViewCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshListTeachers)
                .addContainerGap())
        );
        viewTeachersLayout.setVerticalGroup(
            viewTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTeachersLayout.createSequentialGroup()
                .addGroup(viewTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshListTeachers)
                    .addComponent(eidikotitaViewCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );

        botPanel.add(viewTeachers, "card2");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Φόρμα εισαγωγής νεων καθηγητών"));
        jPanel5.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N

        onomaLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        onomaLabel.setText("Όνομα :");

        eponimoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eponimoTFActionPerformed(evt);
            }
        });

        onomaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onomaTFActionPerformed(evt);
            }
        });

        kataxorisiBtn.setText("Καταχώρηση");
        kataxorisiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kataxorisiBtnActionPerformed(evt);
            }
        });

        eponimoLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        eponimoLabel.setText("Επώνυμο :");

        eidikotitaLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        eidikotitaLabel.setText("Ειδικότητα :");

        eidikotitaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(eidikotita));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kataxorisiBtn)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onomaLabel)
                            .addComponent(eidikotitaLabel)
                            .addComponent(eponimoLabel))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eponimoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(onomaTF)
                            .addComponent(eidikotitaCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onomaLabel)
                    .addComponent(onomaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eponimoLabel)
                    .addComponent(eponimoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eidikotitaLabel)
                    .addComponent(eidikotitaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(kataxorisiBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addTeachersLayout = new javax.swing.GroupLayout(addTeachers);
        addTeachers.setLayout(addTeachersLayout);
        addTeachersLayout.setHorizontalGroup(
            addTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTeachersLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        addTeachersLayout.setVerticalGroup(
            addTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTeachersLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        botPanel.add(addTeachers, "card3");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Φόρμα επεξεργασίας καθηγητών"));
        jPanel6.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new java.awt.GridBagLayout());

        onomaEditLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        onomaEditLabel.setLabelFor(onomaKathigitisEditTF);
        onomaEditLabel.setText("Όνομα :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(onomaEditLabel, gridBagConstraints);

        eponimoKathigitisEditTF.setEnabled(false);
        eponimoKathigitisEditTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eponimoKathigitisEditTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(eponimoKathigitisEditTF, gridBagConstraints);

        onomaKathigitisEditTF.setEnabled(false);
        onomaKathigitisEditTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onomaKathigitisEditTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(onomaKathigitisEditTF, gridBagConstraints);

        epeksergasiaEditBtn.setText("Επεξεργασία");
        epeksergasiaEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epeksergasiaEditBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 39, 20, 0);
        jPanel6.add(epeksergasiaEditBtn, gridBagConstraints);

        eponimoEditLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        eponimoEditLabel.setLabelFor(eponimoKathigitisEditTF);
        eponimoEditLabel.setText("Επώνυμο :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(eponimoEditLabel, gridBagConstraints);

        eidikotitaEditLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        eidikotitaEditLabel.setLabelFor(eidikotitaKathigitisEditCombo);
        eidikotitaEditLabel.setText("Ειδικότητα :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(eidikotitaEditLabel, gridBagConstraints);

        eidikotitaKathigitisEditCombo.setModel(new javax.swing.DefaultComboBoxModel<>(eidikotita));
        eidikotitaKathigitisEditCombo.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(eidikotitaKathigitisEditCombo, gridBagConstraints);

        amEditLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        amEditLabel.setLabelFor(amEditLabel);
        amEditLabel.setText("ΑΜ :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(amEditLabel, gridBagConstraints);

        amKathigitisEditTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                amKathigitisEditTFFocusLost(evt);
            }
        });
        amKathigitisEditTF.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                amKathigitisEditTFPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 9, 0);
        jPanel6.add(amKathigitisEditTF, gridBagConstraints);

        onomaLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        onomaLabel3.setText("Εισαγετε το ΑΜ του καθηγητη που θελετε να επεξεργαστειτε:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 14, 14);
        jPanel6.add(onomaLabel3, gridBagConstraints);

        buttonGroup1.add(diagrafiKathigitiRadio);
        diagrafiKathigitiRadio.setSelected(true);
        diagrafiKathigitiRadio.setText("Διαγραφή Καθηγητή");
        diagrafiKathigitiRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                diagrafiKathigitiRadioItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 9, 0);
        jPanel6.add(diagrafiKathigitiRadio, gridBagConstraints);

        buttonGroup1.add(epeksergasiaKathigitisRadio);
        epeksergasiaKathigitisRadio.setText("Επεξεργασία Καθηγητη");
        epeksergasiaKathigitisRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                epeksergasiaKathigitisRadioItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 9, 0);
        jPanel6.add(epeksergasiaKathigitisRadio, gridBagConstraints);

        javax.swing.GroupLayout editTeachersLayout = new javax.swing.GroupLayout(editTeachers);
        editTeachers.setLayout(editTeachersLayout);
        editTeachersLayout.setHorizontalGroup(
            editTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTeachersLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        editTeachersLayout.setVerticalGroup(
            editTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTeachersLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        botPanel.add(editTeachers, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPanelMouseClicked
        // TODO add your handling code here:
        viewTeachers.setVisible(true);
        addTeachers.setVisible(false);
        editTeachers.setVisible(false);
        viewPanel.setBackground(new java.awt.Color(35,90,190));
        addPanel.setBackground(new java.awt.Color(45,118,232));
        editPanel.setBackground(new java.awt.Color(45,118,232));
        showInTable();
    }//GEN-LAST:event_viewPanelMouseClicked

    private void addPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPanelMouseClicked
        // TODO add your handling code here:
        viewTeachers.setVisible(false);
        addTeachers.setVisible(true);
        editTeachers.setVisible(false);
        viewPanel.setBackground(new java.awt.Color(45,118,232));
        addPanel.setBackground(new java.awt.Color(35,90,190));
        editPanel.setBackground(new java.awt.Color(45,118,232));
    }//GEN-LAST:event_addPanelMouseClicked

    private void eponimoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eponimoTFActionPerformed
        // TODO add your handling code here:
        eidikotitaCombo.requestFocus();
    }//GEN-LAST:event_eponimoTFActionPerformed

    private void refreshListTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshListTeachersActionPerformed
        // TODO add your handling code here:
        showInTable(String.valueOf(eidikotitaViewCombo.getSelectedItem()));
    }//GEN-LAST:event_refreshListTeachersActionPerformed

    private void kataxorisiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kataxorisiBtnActionPerformed
        // TODO add your handling code here:
        KathigitisAdmin.addNewTeacher(onomaTF.getText(), eponimoTF.getText(), String.valueOf(eidikotitaCombo.getSelectedItem()));
        
        
    }//GEN-LAST:event_kataxorisiBtnActionPerformed

    private void onomaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onomaTFActionPerformed
        // TODO add your handling code here:
        eponimoTF.requestFocus();
    }//GEN-LAST:event_onomaTFActionPerformed

    private void editPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPanelMouseClicked
        // TODO add your handling code here:
        viewTeachers.setVisible(false);
        addTeachers.setVisible(false);
        editTeachers.setVisible(true);
        viewPanel.setBackground(new java.awt.Color(45,118,232));
        addPanel.setBackground(new java.awt.Color(45,118,232));
        editPanel.setBackground(new java.awt.Color(35,90,190));
    }//GEN-LAST:event_editPanelMouseClicked

    private void eponimoKathigitisEditTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eponimoKathigitisEditTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eponimoKathigitisEditTFActionPerformed

    private void onomaKathigitisEditTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onomaKathigitisEditTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onomaKathigitisEditTFActionPerformed

    private void epeksergasiaEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epeksergasiaEditBtnActionPerformed
        // TODO add your handling code here:
        if(diagrafiKathigitiRadio.isSelected()){
            editKathigitis(Integer.valueOf(amKathigitisEditTF.getText()),
                            onomaKathigitisEditTF.getText(),
                            eponimoKathigitisEditTF.getText(),
                            String.valueOf(eidikotitaKathigitisEditCombo.getSelectedItem()));
        }else if (epeksergasiaKathigitisRadio.isSelected()){
            deleteKathigitis(Integer.valueOf(amKathigitisEditTF.getText()));
        }
    }//GEN-LAST:event_epeksergasiaEditBtnActionPerformed

    private void epeksergasiaKathigitisRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_epeksergasiaKathigitisRadioItemStateChanged
        // TODO add your handling code here:
        onomaKathigitisEditTF.setEnabled(true);
        eponimoKathigitisEditTF.setEnabled(true);
        eidikotitaKathigitisEditCombo.setEnabled(true);
    }//GEN-LAST:event_epeksergasiaKathigitisRadioItemStateChanged

    private void diagrafiKathigitiRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_diagrafiKathigitiRadioItemStateChanged
        // TODO add your handling code here:
        onomaKathigitisEditTF.setEnabled(false);
        eponimoKathigitisEditTF.setEnabled(false);
        eidikotitaKathigitisEditCombo.setEnabled(false);
    }//GEN-LAST:event_diagrafiKathigitiRadioItemStateChanged

    private void amKathigitisEditTFPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_amKathigitisEditTFPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_amKathigitisEditTFPropertyChange

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        jPanel6.requestFocus();
    }//GEN-LAST:event_jPanel6MousePressed

    private void amKathigitisEditTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amKathigitisEditTFFocusLost
        // TODO add your handling code here:
        showDetailsEdit(amKathigitisEditTF.getText());
    }//GEN-LAST:event_amKathigitisEditTFFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kathigitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kathigitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kathigitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kathigitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kathigitis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel addTeachers;
    private javax.swing.JLabel amEditLabel;
    private javax.swing.JTextField amKathigitisEditTF;
    private javax.swing.JPanel botPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton diagrafiKathigitiRadio;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel editTeachers;
    private javax.swing.JComboBox<String> eidikotitaCombo;
    private javax.swing.JLabel eidikotitaEditLabel;
    private javax.swing.JComboBox<String> eidikotitaKathigitisEditCombo;
    private javax.swing.JLabel eidikotitaLabel;
    private javax.swing.JComboBox<String> eidikotitaViewCombo;
    private javax.swing.JButton epeksergasiaEditBtn;
    private javax.swing.JRadioButton epeksergasiaKathigitisRadio;
    private javax.swing.JLabel eponimoEditLabel;
    private javax.swing.JTextField eponimoKathigitisEditTF;
    private javax.swing.JLabel eponimoLabel;
    private javax.swing.JTextField eponimoTF;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kataxorisiBtn;
    private javax.swing.JLabel onomaEditLabel;
    private javax.swing.JTextField onomaKathigitisEditTF;
    private javax.swing.JLabel onomaLabel;
    private javax.swing.JLabel onomaLabel3;
    private javax.swing.JTextField onomaTF;
    private javax.swing.JButton refreshListTeachers;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JPanel viewTeachers;
    // End of variables declaration//GEN-END:variables

    String eidikotita[] = {"ΚΦΑ","Μαθηματικός","Φυσικός","Χημικός","Φιλόλογος","Βιολόγος","Οικονομολόγος","Πληροφορική"};
    String viewEidikotita[] = {"","ΚΦΑ","Μαθηματικό","Φυσικό","Χημικό","Φιλολογία","Βιολογία","Οικονομικό","Πληροφορική"};
    
    
    
    private void showInTable(String ext){
        if(ext.equals("")){
            showInTable();
        }else{
            try {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                String selectString = "SELECT showtableeidkathigitis(?);";
                PreparedStatement aStatePG = DBPostresqlAdmin.getPrepareStatement(selectString);
                model.setRowCount(0);
                ResultSet rs = DBPostresqlAdmin.getResultset();
                try{
                    aStatePG.setString(1, ext);
                    rs = aStatePG.executeQuery();
                    Object[] row = new Object[4];
                    String columnvalue;
                while (rs.next()) {
                    columnvalue = rs.getString(1);
                    String[] a = columnvalue.substring(1, columnvalue.length()-1).split(",");
                    for (int i = 0; i< a.length; i++) {
                        row[i] =a[i];
                    }
                    System.out.println("15");
                    model.addRow(row);
                    System.out.println("16");
            }
                } catch(SQLException ex) {
                    System.out.println("\n -- SQL Exception --- \n");
                    while(ex != null) {
                        System.out.println("Message: " + ex.getMessage());
                        ex = ex.getNextException();
                    }
                } 
            
            } catch (Exception e) {
            System.out.println("ti pige strava: " + e.getMessage());
            }
        }
        
    }
    private void showInTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String selectString = "SELECT showtablekathigitis();";
        Statement aStatePG = DBPostresqlAdmin.getStatement();
        model.setRowCount(0);
        ResultSet rs = DBPostresqlAdmin.getResultset();
        try {
            rs = aStatePG.executeQuery(selectString);
            Object[] row = new Object[8];
            String columnvalue;
            
            while (rs.next()) {
                columnvalue = rs.getString(1);
                String[] a = columnvalue.substring(1, columnvalue.length()-1).split(",");
                for (int i = 0; i < a.length; i++) {
                    row[i] =a[i];
                }
                model.addRow(row);
            }
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
    }
    
    private void editKathigitis(int ext1, String ext2, String ext3,String ext4){
        String selectString = "SELECT updatekathigitis(?, ?, ?, ?);";
        PreparedStatement aStatePG = DBPostresqlAdmin.getPrepareStatement(selectString);
        
        try {
            aStatePG.setInt(1, ext1);
            aStatePG.setString(2, ext2);
            aStatePG.setString(3, ext3);
            aStatePG.setString(4, ext4);
            aStatePG.executeQuery();
            
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
    }
    
    
        private void deleteKathigitis(int ext){
        String selectString = "SELECT deletekathigitis(?)";
        PreparedStatement aStatePG = DBPostresqlAdmin.getPrepareStatement(selectString);
        try {
            aStatePG.setInt(1, ext);
            aStatePG.executeQuery();
            
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
    }
    
    
    
    private void showDetailsEdit(String ext){
        try {
            int num  = Integer.valueOf(ext);
            if((num< MathitisAdmin.getSid()) && (num >0)){
                String selectString = "SELECT selKathigitisViaID(?);";
                PreparedStatement aStatePG = DBPostresqlAdmin.getPrepareStatement(selectString);
                ResultSet rs = DBPostresqlAdmin.getResultset();
                try {
                    aStatePG.setInt(1, num);
                    rs = aStatePG.executeQuery();        
                    String columnvalue;
                    rs.next();
                    columnvalue = rs.getString(1);   
                    String[] a = columnvalue.substring(1, columnvalue.length()-1).split(",");
                    onomaKathigitisEditTF.setText(a[0]);
                    eponimoKathigitisEditTF.setText(a[1]);
                    for(int i=0; i<eidikotita.length; i++){
                        if(a[2].equals(eidikotita[i])){
                            eidikotitaKathigitisEditCombo.setSelectedIndex(i); 
                            break;
                        }
                    }
                    
                                   
                } catch(SQLException ex) {
                    System.out.println("\n -- SQL Exception --- \n");
                    while(ex != null) {
                        System.out.println("Message: " + ex.getMessage());
                        ex = ex.getNextException();
                    }
                } 
            }else{
                onomaKathigitisEditTF.setText("");
                eponimoKathigitisEditTF.setText("");
                eidikotitaKathigitisEditCombo.setSelectedIndex(0);
                String temp = "<html>To AM που δωσατε ειναι δεν υπαρχει <br>Παρακαλω δωστε αριθμους απο το 1 εως "+ String.valueOf(MathitisAdmin.getSid()-1);
                JOptionPane.showMessageDialog(null, temp, "Προσοχή!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
                onomaKathigitisEditTF.setText("");
                eponimoKathigitisEditTF.setText("");
                eidikotitaKathigitisEditCombo.setSelectedIndex(0);
            String temp = "<html>To AM που δωσατε ειναι δεν υπαρχει <br>Παρακαλω δωστε αριθμους απο το 1 εως "+ String.valueOf(MathitisAdmin.getSid()-1);
            JOptionPane.showMessageDialog(null, temp, "Προσοχή!", JOptionPane.WARNING_MESSAGE);
            System.out.println("ti pige strava: " + e.getMessage());
        }
        
    }
    
    
    
    
    
}
