/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author proxc
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    public Settings() {
        initComponents();
        if(DBPostresqlAdmin.getConnection() != null){
            jPanelPostgresChanger(true);
            postgreUN.setText(DBPostresqlAdmin.getUsername());
            postgrePW.setText(DBPostresqlAdmin.getPassword());
            isConnectedPostgre = !isConnectedPostgre;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        postgreUN = new javax.swing.JTextField();
        postgreEntrance = new javax.swing.JButton();
        isConnectedPostgreLabel = new javax.swing.JLabel();
        postgrePW = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/w_settings_50px.png"))); // NOI18N
        jLabel15.setText("Ρυθμίσεις");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Postgre SQL"));

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        postgreUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgreUNActionPerformed(evt);
            }
        });

        postgreEntrance.setText("Είσοδος");
        postgreEntrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgreEntranceActionPerformed(evt);
            }
        });

        isConnectedPostgreLabel.setText("Μη συνδεδεμένη");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postgreUN, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(postgrePW))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(postgreEntrance)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(isConnectedPostgreLabel)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isConnectedPostgreLabel)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(postgreUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(postgrePW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(postgreEntrance)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void postgreUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgreUNActionPerformed
        // TODO add your handling code here:
        postgrePW.requestFocus();
    }//GEN-LAST:event_postgreUNActionPerformed

    private void postgreEntranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgreEntranceActionPerformed
        // TODO add your handling code here:
        if (!isConnectedPostgre){
            if(enterToPostrgres()){
                jPanelPostgresChanger(true);
                isConnectedPostgre = !isConnectedPostgre;
                this.setVisible(false);
            }
        }else{
            jPanelPostgresChanger(!DBPostresqlAdmin.closeit());
            isConnectedPostgre = !isConnectedPostgre;
        }

        
    }//GEN-LAST:event_postgreEntranceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel isConnectedPostgreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton postgreEntrance;
    private javax.swing.JPasswordField postgrePW;
    private javax.swing.JTextField postgreUN;
    // End of variables declaration//GEN-END:variables
    // { Start of } Variables
    boolean isConnectedPostgre = false;

    DBPostresqlAdmin dbpg;
    Statement psql = dbpg.getStatement();

    // { End of }   Variables
    


    
// Methods
// { Start of } DB methods

    private boolean enterToPostrgres(){
        //postgreErrorLabel.setText("");
            dbpg = new DBPostresqlAdmin(postgreUN.getText(), postgrePW.getText());
            dbpg.connectToDB();
            tableController();
            if(dbpg.isConnected()){
                return true;
            }else{
                JOptionPane.showMessageDialog(null, "Ελεγξτε το Username ή/και το Password" , 
                        "Ενημέρωση", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            
            
                
            
            
    }
    
    private void jPanelPostgresChanger(boolean isConnected){
        if (isConnected == true){
            isConnectedPostgreLabel.setForeground(Color.GREEN);
            isConnectedPostgreLabel.setText("Συνδεδεμένη");
            postgreUN.setEnabled(!isConnected);
            postgrePW.setEnabled(!isConnected);
            postgreEntrance.setText("Έξοδος");
            Home.enableUI = true;
            
        }else if(isConnected == false){
            postgreEntrance.setText("Είσοδος");
            postgreUN.setEnabled(!isConnected);
            postgrePW.setEnabled(!isConnected);
            isConnectedPostgreLabel.setText("Μη συνδεδεμένη");
            isConnectedPostgreLabel.setForeground(Color.BLACK);
            Home.enableUI = false;
        }

    }
    
    // {End of} DB methods
    
    // {Start Method} Enter to main window


    
    
    
    private void tableController(){
        
        // Drop Procedures
        StoredProceduresAdmin.dropStoreProcedures();
        
        // Drop Tables
        dropTablesPG();
        
        // Create Tables
        createTablesPG();
        
        // Create Procedures
        StoredProceduresAdmin.createStoreProcedures();
        
        
    }
    private void dropTablesPG() {
        Statement psql = dbpg.getStatement();
        try {psql.executeUpdate("DROP TABLE vathmologia");} catch (SQLException e) {System.out.println(e.getMessage());}
        try {psql.executeUpdate("DROP TABLE mathima");} catch (SQLException e) {System.out.println(e.getMessage());}
        try {psql.executeUpdate("DROP TABLE mathitis");} catch (SQLException e) {System.out.println(e.getMessage());}
        try {psql.executeUpdate("DROP TABLE kathigitis");} catch (SQLException e) {System.out.println(e.getMessage());}
       
        
    
    }
    
    private void createTablesPG(){
        new MathitisAdmin();
        new KathigitisAdmin();
        new MathimaAdmin();
        new VathmologiaAdmin();
    }
}
