/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author proxc
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    public Settings() {
        initComponents();
    }
    public Settings(int i){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        postgreUN = new javax.swing.JTextField();
        postgreEntrance = new javax.swing.JButton();
        isConnectedPostgreLabel = new javax.swing.JLabel();
        postgrePW = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oraclePW = new javax.swing.JTextField();
        oracleEntrance = new javax.swing.JButton();
        isConnectedOracleLabel = new javax.swing.JLabel();
        oracleUN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/w_settings_50px.png"))); // NOI18N
        jLabel15.setText("Ρυθμήσεις");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Postgre SQL"));

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        postgreUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgreUNActionPerformed(evt);
            }
        });

        postgreEntrance.setText("Είσοδος");
        postgreEntrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgreEntranceActionPerformed(evt);
            }
        });

        isConnectedPostgreLabel.setText("Μη συνδεδεμένη");

        postgrePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgrePWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postgreUN, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(postgrePW))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(postgreEntrance)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(isConnectedPostgreLabel)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isConnectedPostgreLabel)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(postgreUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(postgrePW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(postgreEntrance)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Oracle SQL"));

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        oraclePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oraclePWActionPerformed(evt);
            }
        });

        oracleEntrance.setText("Είσοδος");
        oracleEntrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oracleEntranceActionPerformed(evt);
            }
        });

        isConnectedOracleLabel.setText("Μη συνδεδεμένη");

        oracleUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oracleUNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oraclePW, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(oracleUN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(oracleEntrance)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(isConnectedOracleLabel)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isConnectedOracleLabel)
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(oracleUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(oraclePW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(oracleEntrance)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postgreUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgreUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postgreUNActionPerformed

    private void postgrePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgrePWActionPerformed
        // TODO add your handling code here:
        postgreEntrance();
    }//GEN-LAST:event_postgrePWActionPerformed

    private void oracleUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oracleUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oracleUNActionPerformed

    private void oracleEntranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oracleEntranceActionPerformed
        // TODO add your handling code here:
        oracleEntrance();
    }//GEN-LAST:event_oracleEntranceActionPerformed

    private void oraclePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oraclePWActionPerformed
        // TODO add your handling code here:
        oracleEntrance();
    }//GEN-LAST:event_oraclePWActionPerformed

    private void postgreEntranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgreEntranceActionPerformed
        // TODO add your handling code here:
        postgreEntrance();
        
    }//GEN-LAST:event_postgreEntranceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel isConnectedOracleLabel;
    private javax.swing.JLabel isConnectedPostgreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton oracleEntrance;
    private javax.swing.JTextField oraclePW;
    private javax.swing.JTextField oracleUN;
    private javax.swing.JButton postgreEntrance;
    private javax.swing.JPasswordField postgrePW;
    private javax.swing.JTextField postgreUN;
    // End of variables declaration//GEN-END:variables
    // { Start of } Variables
    
    DBOracleAdmin dbor;
    DBPostresqlAdmin dbpg;
    static int sidIncr = 1;
    
    // { End of }   Variables
    
    static int sidIncreament(){
        return sidIncr++;
    }

    
// Methods
// { Start of } DB methods
    private void oracleEntrance(){
       // oracleErrorLabel.setText("");
        dbor = new DBOracleAdmin(oracleUN.getText(), oraclePW.getText());
        Statement test = dbor.connectToDB();
            if(test != null){
                
                isConnectedOracleLabel.setText("Συνδεδεμένη");
                oracleEntrance.setEnabled(false);
            }else{
                String a = "<html>Ελεγξτε το Username ή το Password<br>Ελεγξτε τη συνδεση VPN";
                JOptionPane.showMessageDialog(new JFrame(), a, "Σφάλμα", HEIGHT);
                
            }
    }
    private void postgreEntrance(){
        //postgreErrorLabel.setText("");
            dbpg = new DBPostresqlAdmin(postgreUN.getText(), postgrePW.getText());
            Statement test = dbpg.connectToDB();
            if(test != null){
                isConnectedPostgreLabel.setForeground(Color.GREEN);
                isConnectedPostgreLabel.setText("Συνδεδεμένη");
                postgreEntrance.setEnabled(false);
                dropTablesPG();
                createTablesPG();
//                insertToMathitis();
            }else{
               // postgreErrorLabel.setText("Ελεγξτε το Username ή το Password");
            }
    }
    
    public DBPostresqlAdmin giveIt(){
        return dbpg;
    }
    // {End of} DB methods
    
    // {Start Method} Enter to main window

    void dropTablesPG() {
        Statement psql = dbpg.getStatement();
        try {psql.executeUpdate("DROP TABLE vathmologia");} catch (SQLException e) {}
        try {psql.executeUpdate("DROP TABLE mathima");} catch (SQLException e) {}
        try {psql.executeUpdate("DROP TABLE mathitis");} catch (SQLException e) {}
        try {psql.executeUpdate("DROP TABLE kathigitis");} catch (SQLException e) {}
    }
    
    void createTablesPG(){
        Statement aStatePG = dbpg.getStatement();

        StudentAdmin a = new StudentAdmin();
        
        String query2 = "CREATE TABLE kathigitis(\n" +
                        "kid int NOT NULL, \n" +
                        "Onoma_kathigiti varchar(20),\n" +
                        "Epitheto_kathigiti varchar(20), \n" +
                        "Eidikotita varchar(20),\n" +
                        "PRIMARY KEY(kid)\n" +
                        ");";        
        
        
        
        String query3 = "CREATE TABLE mathima(\n" +
                        "mid int NOT NULL,\n" +
                        "Kid INT NOT NULL,\n" +
                        "mathima varchar(20),\n" +
                        "PRIMARY KEY(mid),\n" +
                        "FOREIGN KEY (kid) REFERENCES kathigitis(kid)\n" +
                        ");";
        
        String query4 = "CREATE TABLE vathmologia(\n" +
                        "sid int NOT NULL, \n" +
                        "mid int NOT NULL, \n" +
                        "vathmos int,\n" +
                        "etos varchar(50),\n" +
                        "FOREIGN KEY (sid) REFERENCES mathitis(sid),\n" +
                        "FOREIGN KEY (mid) REFERENCES mathima(mid)\n" +
                        ");";
        
        try {aStatePG.executeUpdate(query2);} catch (Exception e) {System.out.println("Create table : " + e.toString());}
        try {aStatePG.executeUpdate(query3);} catch (Exception e) {System.out.println("Create table : " + e.toString());}
        try {aStatePG.executeUpdate(query4);} catch (Exception e) {System.out.println("Create table : " + e.toString());}
        
            
        
    }
        
    
    

    
    
    
    
    
    
    
     void addNewStudent(String onoma, String eponymo, String onomaPatera, String onomaMiteras, int etosEisagwgis){
        String addQuery = "INSERT INTO mathitis(sid, onoma, eponymo, onPateras, onMiteras, etosEisagogis) VALUES (?, ?, ?, ?, ?, ?)";
            
            
        try {
        PreparedStatement aStatePG = dbpg.getPrepareStatement(addQuery);
            for(int i =0; i < 8; i++ ){
                aStatePG.setInt(1,Settings.sidIncreament());
                aStatePG.setString(2, onoma);
                aStatePG.setString(3, eponymo);
                aStatePG.setString(4, onomaPatera);
                aStatePG.setString(5, onomaMiteras);
                aStatePG.setInt(6, etosEisagwgis);
                aStatePG.executeUpdate();
                System.out.println("Mpike");
                
            }
        } catch (Exception e) {
            System.out.println("pirame to mpoylo des kai to logo " + e.toString());
        }        
        
    }

    
    
    
    



}
