
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form first
     */
    public Welcome() {
        initComponents();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        appEntrance = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        postgreUN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        postgrePW = new javax.swing.JPasswordField();
        postgreEntrance = new javax.swing.JButton();
        isConnectedPostgreLabel = new javax.swing.JLabel();
        postgreErrorLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        oracleUN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        oraclePW = new javax.swing.JPasswordField();
        oracleEntrance = new javax.swing.JButton();
        isConnectedOracleLabel = new javax.swing.JLabel();
        oracleErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        appEntrance.setLabel("Εισοδος στην εφαρμογή");
        appEntrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appEntranceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 15, 0);
        getContentPane().add(appEntrance, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PostgreSQL"));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 0, 11);
        jPanel1.add(postgreUN, gridBagConstraints);

        jLabel3.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 18, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 17, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 11);
        jPanel1.add(postgrePW, gridBagConstraints);

        postgreEntrance.setText("Εισοδος στην PostgreSQL");
        postgreEntrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgreEntranceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 5, 0);
        jPanel1.add(postgreEntrance, gridBagConstraints);

        isConnectedPostgreLabel.setText("Μη συνδεδεμένη");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 11);
        jPanel1.add(isConnectedPostgreLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel1.add(postgreErrorLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 23);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Oracle SQL"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 18, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        oracleUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oracleUNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 0, 11);
        jPanel2.add(oracleUN, gridBagConstraints);

        jLabel6.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 17, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 11);
        jPanel2.add(oraclePW, gridBagConstraints);

        oracleEntrance.setText("Εισοδος στην Oracle SQL");
        oracleEntrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oracleEntranceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 8, 0);
        jPanel2.add(oracleEntrance, gridBagConstraints);

        isConnectedOracleLabel.setText("Μη συνδεδεμένη");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 11);
        jPanel2.add(isConnectedOracleLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel2.add(oracleErrorLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 15);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void appEntranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appEntranceActionPerformed
        enterToMain();   
    }//GEN-LAST:event_appEntranceActionPerformed

    private void oracleUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oracleUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oracleUNActionPerformed

    private void postgreEntranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgreEntranceActionPerformed
        postgreEntrance();

    }//GEN-LAST:event_postgreEntranceActionPerformed

    private void oracleEntranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oracleEntranceActionPerformed
        oracleEntrance();
    }//GEN-LAST:event_oracleEntranceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appEntrance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel isConnectedOracleLabel;
    private javax.swing.JLabel isConnectedPostgreLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton oracleEntrance;
    private javax.swing.JLabel oracleErrorLabel;
    private javax.swing.JPasswordField oraclePW;
    private javax.swing.JTextField oracleUN;
    private javax.swing.JButton postgreEntrance;
    private javax.swing.JLabel postgreErrorLabel;
    private javax.swing.JPasswordField postgrePW;
    private javax.swing.JTextField postgreUN;
    // End of variables declaration//GEN-END:variables


    DBOracleAdmin oracleDB;
    DBPostresqlAdmin postgresDB;

// Methods
// DB methods
    private void oracleEntrance(){
        oracleErrorLabel.setText("");
            oracleDB = new DBOracleAdmin(oracleUN.getText(), oraclePW.getText());
            Statement test = oracleDB.connectToDB();
            if(test != null){
                isConnectedOracleLabel.setText("Συνδεδεμένη");
                oracleEntrance.setEnabled(false);
            }else{
                oracleErrorLabel.setText("Ελεγξτε το Username ή το Password");
            }
    }
    private void postgreEntrance(){
        postgreErrorLabel.setText("");
            postgresDB = new DBPostresqlAdmin(postgreUN.getText(), postgrePW.getText());
            Statement test = postgresDB.connectToDB();
            if(test != null){
                isConnectedPostgreLabel.setText("Συνδεδεμένη");
                postgreEntrance.setEnabled(false);
            }else{
                postgreErrorLabel.setText("Ελεγξτε το Username ή το Password");
            }     
        

        
        
    }

// Enter to main window

    private void enterToMain(){
            try {
//                Statement psql = postgresDB.getStatement();
//                psql.executeUpdate("DROP TABLE persons");
                
                if(isConnectedPostgreLabel.getText().equals("Συνδεδεμένη")){
                    postgresDB.closeit();
                }
                if(isConnectedOracleLabel.getText().equals("Συνδεδεμένη")){
                    oracleDB.closeit();
                }                   
                new MainWindow().setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
                System.out.println("ti malakia paixtike? " + e.toString());
            }

    }


}
